(function () {
    const questions = [
        { topic: 'Constructor', text: 'Trong class Car, dòng khai báo nào đúng là constructor không tham số?', options: ['public Car() { }', 'public void Car() { }', 'public constructor Car() { }', 'Car public() { }'], correct: 0, explanation: 'Constructor trùng tên class và không có kiểu trả về.' },
        { topic: 'Constructor', text: 'Class Employee có field name và id. Constructor nào khởi tạo đúng cả hai field?', options: ['public Employee(string name, int id) { this.name = name; this.id = id; }', 'public void Employee(string name, int id) { this.name = name; this.id = id; }', 'public Employee() { name = id; }', 'static Employee(string name, int id) { this.name = name; }'], correct: 0, explanation: 'Constructor instance không có void và có thể dùng this để phân biệt field với tham số.' },
        { topic: 'Constructor', text: 'Class Student chỉ có public Student(string name). Dòng nào sẽ gây lỗi biên dịch?', options: ['Student s = new Student();', 'Student s = new Student("An");', 'var s = new Student("Binh");', 'Student s2 = new Student(name: "Lan");'], correct: 0, explanation: 'Khi đã khai báo constructor có tham số, default constructor không tham số không còn tự sinh.' },
        { topic: 'Constructor', text: 'Bạn có public Car() : this("No name", 0) { }. Ý nghĩa của this("No name", 0) là gì?', options: ['Gọi constructor khác trong cùng class Car', 'Gọi constructor của class cha', 'Tạo một namespace tên Car', 'Gọi static constructor của Car'], correct: 0, explanation: 'this(...) dùng để chaining sang constructor khác cùng class.' },
        { topic: 'Constructor', text: 'Manager kế thừa Employee, Employee có Employee(string name, int id). Constructor Manager nào đúng?', options: ['public Manager(string name, int id, int level) : base(name, id) { this.level = level; }', 'public Manager(string name, int id, int level) : this(name, id) { this.level = level; }', 'public Manager(string name, int id, int level) { base(name, id); }', 'public void Manager(string name, int id, int level) : base(name, id) { }'], correct: 0, explanation: 'base(...) phải đặt trong initializer của constructor class con.' },
        { topic: 'Constructor', text: 'Static constructor của class Database nên viết như thế nào?', options: ['static Database() { connectionString = "..."; }', 'public static Database(string cs) { connectionString = cs; }', 'private void Database() { connectionString = "..."; }', 'static void Database() { connectionString = "..."; }'], correct: 0, explanation: 'Static constructor không có access modifier, không tham số và không có kiểu trả về.' },
        { topic: 'Constructor', text: 'Field readonly int id cần nhận giá trị từ tham số constructor. Dòng nào hợp lệ?', options: ['public Student(int id) { this.id = id; }', 'public void SetId(int id) { this.id = id; }', 'public int Id { set { id = value; } }', 'static void ChangeId(int id) { this.id = id; }'], correct: 0, explanation: 'Readonly instance field được gán trong constructor instance.' },
        { topic: 'Constructor', text: 'Class Logger muốn không cho code ngoài gọi new Logger(). Cách nào đúng nhất?', options: ['Khai báo private Logger() { }', 'Khai báo public Logger() { }', 'Xóa toàn bộ constructor khỏi class', 'Khai báo public void Logger() { }'], correct: 0, explanation: 'Private constructor chặn việc tạo object trực tiếp từ bên ngoài.' },

        { topic: 'Properties', text: 'Property nào chặn tuổi âm khi gán Age?', options: ['set { if (value >= 0) age = value; }', 'get { if (age >= 0) age = value; }', 'set { if (age < 0) age = value; }', 'get { return value; }'], correct: 0, explanation: 'Setter dùng value để kiểm tra dữ liệu trước khi gán vào field.' },
        { topic: 'Properties', text: 'Bạn muốn bên ngoài đọc ID nhưng chỉ class Employee được sửa ID. Khai báo nào đúng?', options: ['public int ID { get; private set; }', 'private int ID { get; set; }', 'public int ID { private get; set; }', 'public int ID;'], correct: 0, explanation: 'get public, set private tạo property đọc công khai nhưng ghi nội bộ.' },
        { topic: 'Properties', text: 'Dòng emp.ID = 1234; sẽ gọi phần nào trong property ID?', options: ['set của property ID', 'get của property ID', 'constructor của Employee', 'static constructor của Employee'], correct: 0, explanation: 'Gán giá trị cho property sẽ chạy setter.' },
        { topic: 'Properties', text: 'Dòng Console.WriteLine(emp.ID); sẽ gọi phần nào trong property ID?', options: ['get của property ID', 'set của property ID', 'constructor của Employee', 'method ToString của class Employee bắt buộc'], correct: 0, explanation: 'Đọc giá trị property sẽ chạy getter.' },
        { topic: 'Properties', text: 'Automatic property nào đúng cú pháp?', options: ['public string Name { get; set; }', 'public string Name get; set;', 'public Name string { get; set; }', 'public string Name() { get; set; }'], correct: 0, explanation: 'Automatic property có cặp accessor get/set trong dấu ngoặc nhọn.' },
        { topic: 'Properties', text: 'Property public int Port { get; init; } cho phép gán khi nào?', options: ['Khi khởi tạo object, ví dụ new Config { Port = 8080 }', 'Bất kỳ lúc nào sau khi object đã tạo', 'Chỉ bên trong getter', 'Chỉ trong static method'], correct: 0, explanation: 'init cho phép đặt giá trị trong giai đoạn khởi tạo object.' },
        { topic: 'Properties', text: 'Vì sao không nên để public int empID trong Employee?', options: ['Code ngoài có thể gán empID = -5 mà không qua kiểm tra', 'public field không thể lưu số nguyên', 'public field chỉ dùng được trong static class', 'public field tự động biến thành readonly'], correct: 0, explanation: 'Public field phá vỡ đóng gói và không kiểm soát dữ liệu vào.' },
        { topic: 'Properties', text: 'Setter nào giữ salary không nhỏ hơn 0?', options: ['set { salary = value < 0 ? 0 : value; }', 'set { salary = -value; }', 'get { salary = value; }', 'set { value = salary; }'], correct: 0, explanation: 'Setter có thể chuẩn hóa dữ liệu trước khi lưu vào field.' },

        { topic: 'Static', text: 'Trong class Student, schoolName dùng chung cho mọi sinh viên nên khai báo thế nào?', options: ['public static string schoolName;', 'public string schoolName;', 'private readonly string schoolName;', 'public const Student schoolName;'], correct: 0, explanation: 'Dữ liệu dùng chung cấp class nên là static field.' },
        { topic: 'Static', text: 'currBalance của SavingsAccount là số dư riêng từng tài khoản. Khai báo nào hợp lý?', options: ['public double currBalance;', 'public static double currBalance;', 'public const double currBalance;', 'static class currBalance { }'], correct: 0, explanation: 'Số dư riêng là instance field, không nên static.' },
        { topic: 'Static', text: 'Cách gọi đúng static method PrintInterestRate của SavingsAccount là gì?', options: ['SavingsAccount.PrintInterestRate();', 'new SavingsAccount.PrintInterestRate();', 'SavingsAccount s; s.PrintInterestRate();', 'PrintInterestRate.SavingsAccount();'], correct: 0, explanation: 'Static method được gọi qua tên class.' },
        { topic: 'Static', text: 'Trong static method, dòng nào truy cập hợp lệ nếu currInterestRate là static field?', options: ['Console.WriteLine(currInterestRate);', 'Console.WriteLine(this.currInterestRate);', 'Console.WriteLine(currBalance); // currBalance instance', 'base.currInterestRate = 0.05;'], correct: 0, explanation: 'Static method truy cập trực tiếp được static member cùng class.' },
        { topic: 'Static', text: 'Class MathHelper chỉ có Add, Subtract, Multiply và không cần lưu trạng thái. Thiết kế nào hợp lý?', options: ['static class MathHelper với các static method', 'class MathHelper với public field cho từng phép tính', 'class MathHelper kế thừa từ int', 'private class MathHelper bắt buộc tạo object'], correct: 0, explanation: 'Utility class không cần object thường được thiết kế static.' },
        { topic: 'Static', text: 'Sau Student.schoolName = "HCM"; s1 và s2 đều in schoolName. Kết quả đúng là gì?', options: ['Cả s1 và s2 đều thấy "HCM"', 'Chỉ s1 thấy "HCM"', 'Chỉ s2 thấy "HCM"', 'Không object nào thấy vì static không lưu dữ liệu'], correct: 0, explanation: 'Static field dùng chung cho tất cả object.' },
        { topic: 'Static', text: 'Method thường PrintStudent trong Student có thể truy cập trực tiếp gì?', options: ['Cả name instance field và schoolName static field', 'Chỉ schoolName static field', 'Chỉ biến cục bộ trong Main', 'Không truy cập được field nào'], correct: 0, explanation: 'Instance method có object hiện tại nên dùng được instance member và static member.' },
        { topic: 'Static', text: 'Lỗi chính của static void AddBalance(double amount) { currBalance += amount; } là gì nếu currBalance không static?', options: ['Static method không biết currBalance của object nào để sửa', 'double không dùng được trong static method', 'Toán tử += không dùng được với double', 'Static method không được có tham số'], correct: 0, explanation: 'Static method không có this nên không truy cập trực tiếp instance field.' },

        { topic: 'Phương thức', text: 'Method nào trả tổng hai số nguyên đúng cú pháp?', options: ['public int Add(int a, int b) { return a + b; }', 'public void Add(int a, int b) { return a + b; }', 'public Add int(int a, int b) { return a + b; }', 'public int Add(int a, int b) { Console.WriteLine(a + b); }'], correct: 0, explanation: 'Method trả int phải khai báo int và return một giá trị int.' },
        { topic: 'Phương thức', text: 'Method chỉ in "Hello" ra màn hình nên khai báo kiểu trả về nào?', options: ['void', 'int', 'string', 'bool'], correct: 0, explanation: 'void dùng cho method không trả về dữ liệu.' },
        { topic: 'Phương thức', text: 'Cặp method nào là overloading hợp lệ?', options: ['Print(string text) và Print(int number)', 'Print(string text) và Show(string text)', 'int Add(int a, int b) và float Add(int x, int y)', 'Print() và private Print() cùng không tham số'], correct: 0, explanation: 'Overloading cần cùng tên và khác danh sách tham số.' },
        { topic: 'Phương thức', text: 'Không thể overload hai method chỉ khác điểm nào?', options: ['Chỉ khác kiểu trả về', 'Khác số lượng tham số', 'Khác kiểu tham số', 'Khác thứ tự kiểu tham số'], correct: 0, explanation: 'Kiểu trả về không đủ để phân biệt overload.' },
        { topic: 'Phương thức', text: 'Car có public void SpeedUp(int delta). Dòng gọi nào đúng?', options: ['Car c = new Car(); c.SpeedUp(10);', 'Car.SpeedUp(10);', 'SpeedUp.Car(10);', 'new SpeedUp(Car, 10);'], correct: 0, explanation: 'Non-static method cần gọi qua object.' },
        { topic: 'Phương thức', text: 'Method static int Square(int x) nên được gọi thế nào nếu nằm trong MathHelper?', options: ['MathHelper.Square(5)', 'new MathHelper.Square(5)', 'Square.MathHelper(5)', 'MathHelper().Square(5)'], correct: 0, explanation: 'Static method gọi bằng tên class.' },
        { topic: 'Phương thức', text: 'Trong public void SetName(string name), name là gì?', options: ['Tham số của method', 'Field static mặc định', 'Constructor của class', 'Namespace của chương trình'], correct: 0, explanation: 'Biến trong danh sách ngoặc tròn của method là tham số.' },
        { topic: 'Phương thức', text: 'Gọi Add(1, 2, 3) khi có Add(int,int) và Add(int,int,int), compiler chọn method nào?', options: ['Add(int,int,int)', 'Add(int,int)', 'Cả hai cùng chạy', 'Không method nào vì số 3 không hợp lệ'], correct: 0, explanation: 'Compiler chọn overload khớp số lượng tham số.' },

        { topic: 'Class và object', text: 'Dòng nào tạo một object Car mới?', options: ['Car myCar = new Car();', 'class Car { }', 'Car myCar;', 'namespace Car { }'], correct: 0, explanation: 'new Car() tạo object từ class Car.' },
        { topic: 'Class và object', text: 'Trong class Car { public int currSpeed; }, currSpeed là gì?', options: ['Field của class Car', 'Constructor của class Car', 'Namespace của Car', 'Kiểu dữ liệu mới bắt buộc static'], correct: 0, explanation: 'Biến khai báo trực tiếp trong class là field.' },
        { topic: 'Class và object', text: 'Hai object Car c1 và c2 có non-static field currSpeed. c1.currSpeed = 80 thì c2.currSpeed ra sao?', options: ['Không đổi theo c1', 'Tự động thành 80', 'Bị xóa khỏi bộ nhớ', 'Không đọc được vì mọi field đều static'], correct: 0, explanation: 'Instance field thuộc từng object riêng.' },
        { topic: 'Class và object', text: 'Class dùng để làm gì trong OOP?', options: ['Mô tả khuôn mẫu dữ liệu và hành vi để tạo object', 'Chỉ để gom using System', 'Chỉ để đặt tên file .cs', 'Để thay thế mọi method static'], correct: 0, explanation: 'Class là blueprint cho object.' },
        { topic: 'Class và object', text: 'Bạn muốn code ngoài không sửa trực tiếp speed nhưng vẫn đọc được tốc độ. Thiết kế nào tốt hơn?', options: ['private int speed; public int Speed { get { return speed; } }', 'public int speed;', 'static int speed; public void Speed() { }', 'namespace speed { }'], correct: 0, explanation: 'Private field kết hợp property đọc giúp giữ đóng gói.' },
        { topic: 'Class và object', text: 'Dấu chấm trong myCar.PrintState() có ý nghĩa gì?', options: ['Truy cập member PrintState của object myCar', 'Khai báo kế thừa từ PrintState', 'Ép kiểu myCar thành method', 'Tạo constructor mặc định'], correct: 0, explanation: 'Dấu chấm dùng để truy cập member của object hoặc class.' },

        { topic: 'Kiểu dữ liệu', text: 'Biến nào phù hợp để lưu điểm số nguyên 0 đến 10?', options: ['int score;', 'bool score;', 'char score;', 'namespace score;'], correct: 0, explanation: 'Điểm nguyên nên dùng kiểu số nguyên như int.' },
        { topic: 'Kiểu dữ liệu', text: 'Biến nào phù hợp để lưu kết quả đã qua môn hay chưa?', options: ['bool passed;', 'double passed;', 'char passed;', 'int[] passed;'], correct: 0, explanation: 'bool lưu giá trị true/false.' },
        { topic: 'Kiểu dữ liệu', text: 'Biến nào phù hợp để lưu ký tự xếp loại A?', options: ['char grade = \'A\';', 'bool grade = \'A\';', 'int grade = "A";', 'double grade = true;'], correct: 0, explanation: 'char dùng dấu nháy đơn và lưu một ký tự.' },
        { topic: 'Kiểu dữ liệu', text: 'Chuyển short s = 10; int i = s; thuộc loại nào?', options: ['Chuyển đổi ngầm định từ kiểu nhỏ sang kiểu lớn', 'Chuyển đổi tường minh bắt buộc', 'Ép kiểu gây mất dữ liệu chắc chắn', 'Boxing từ class sang struct'], correct: 0, explanation: 'short sang int là implicit conversion an toàn.' },
        { topic: 'Kiểu dữ liệu', text: 'Dòng nào cần ép kiểu tường minh?', options: ['short s = (short)number; // number là int', 'int i = shortValue;', 'double d = intValue;', 'object o = "abc";'], correct: 0, explanation: 'int sang short có nguy cơ mất dữ liệu nên cần cast.' },
        { topic: 'Kiểu dữ liệu', text: 'checked { byte b = (byte)256; } sẽ thế nào?', options: ['Ném lỗi tràn dữ liệu khi chạy', 'Gán b = 256 thành công', 'Tự đổi b thành string', 'Compiler bỏ qua khối checked'], correct: 0, explanation: 'checked phát hiện overflow trong phép ép kiểu số.' },
        { topic: 'Kiểu dữ liệu', text: 'Giá trị mặc định của bool field là gì?', options: ['false', 'true', 'null', '0.0'], correct: 0, explanation: 'bool mặc định là false.' },
        { topic: 'Kiểu dữ liệu', text: 'Giá trị mặc định của string field khi chưa gán là gì?', options: ['null', '""', 'false', '0'], correct: 0, explanation: 'string là reference type nên mặc định null.' },

        { topic: 'Reference type', text: 'Student a = new Student(); Student b = a; b.Name = "Lan"; a.Name là gì?', options: ['"Lan"', 'null vì a bị mất object', '"An" mặc định', 'Lỗi vì reference type không gán được'], correct: 0, explanation: 'a và b cùng tham chiếu một object.' },
        { topic: 'Reference type', text: 'int x = 5; Increase(x); nếu Increase(int n) { n++; } thì x còn bao nhiêu?', options: ['5', '6', '0', 'null'], correct: 0, explanation: 'int truyền mặc định theo giá trị nên method chỉ đổi bản sao.' },
        { topic: 'Reference type', text: 'int x = 5; Increase(ref x); nếu Increase(ref int n) { n++; } thì x là bao nhiêu?', options: ['6', '5', '0', 'null'], correct: 0, explanation: 'ref cho method thay đổi trực tiếp biến gốc.' },
        { topic: 'Reference type', text: 'Car c = new Car(); SetSpeed(c); method SetSpeed(Car car) { car.Speed = 70; }. Sau đó c.Speed là gì?', options: ['70', '0 vì object truyền theo bản sao độc lập', 'null', 'Lỗi vì object không truyền vào method được'], correct: 0, explanation: 'Biến reference được copy, nhưng vẫn trỏ đến cùng object.' },
        { topic: 'Reference type', text: 'Dòng Student s = null; nghĩa là gì?', options: ['s không tham chiếu object Student nào', 's là object Student rỗng đã được tạo', 's có tất cả field bằng 0', 's tự gọi constructor mặc định'], correct: 0, explanation: 'null biểu thị biến reference không trỏ tới object.' },
        { topic: 'Reference type', text: 'Muốn Swap(ref int a, ref int b) đổi hai biến bên ngoài, khi gọi cần viết gì?', options: ['Swap(ref x, ref y);', 'Swap(x, y);', 'Swap(out x + y);', 'Swap(reference x, reference y);'], correct: 0, explanation: 'Tham số ref yêu cầu dùng ref cả nơi khai báo và nơi gọi.' },

        { topic: 'Using và Console', text: 'Muốn viết Console.WriteLine("Hi"); mà không ghi System.Console, cần using nào?', options: ['using System;', 'using Console;', 'using WriteLine;', 'using System.Console.WriteLine;'], correct: 0, explanation: 'Console nằm trong namespace System.' },
        { topic: 'Using và Console', text: 'Không có using System;, dòng nào vẫn in được "Hi"?', options: ['System.Console.WriteLine("Hi");', 'Console.System.WriteLine("Hi");', 'WriteLine.Console("Hi");', 'System.WriteLine.Console("Hi");'], correct: 0, explanation: 'Có thể dùng tên đầy đủ System.Console.' },
        { topic: 'Using và Console', text: 'Dòng nào đọc một dòng người dùng nhập từ console?', options: ['string name = Console.ReadLine();', 'string name = Console.WriteLine();', 'int name = Console.Print();', 'Console.Input(name);'], correct: 0, explanation: 'Console.ReadLine đọc một dòng và trả về string.' },
        { topic: 'Using và Console', text: 'Muốn dùng List<int> mà không viết đầy đủ namespace, cần using nào?', options: ['using System.Collections.Generic;', 'using System.List;', 'using Collections.List;', 'using System.Array;'], correct: 0, explanation: 'List<T> nằm trong System.Collections.Generic.' },
        { topic: 'Using và Console', text: 'namespace School.Models dùng để làm gì?', options: ['Nhóm các class liên quan và tránh trùng tên', 'Tự động tạo object cho mọi class', 'Bắt buộc mọi class thành static', 'Thay thế constructor của class'], correct: 0, explanation: 'Namespace tổ chức kiểu dữ liệu trong chương trình.' },
        { topic: 'Using và Console', text: 'Dòng nào in biến age kèm nhãn rõ ràng?', options: ['Console.WriteLine($"Age: {age}");', 'Console.ReadLine($"Age: {age}");', 'using Console.WriteLine(age);', 'namespace Console { age }'], correct: 0, explanation: 'String interpolation dùng được trong Console.WriteLine.' },

        { topic: 'Enum', text: 'Bạn có trạng thái Start, Playing, Paused, GameOver. Khai báo nào đúng?', options: ['enum GameState { Start, Playing, Paused, GameOver }', 'array GameState { Start, Playing }', 'list enum GameState = Start;', 'class enum GameState()'], correct: 0, explanation: 'Enum đặt tên cho tập giá trị cố định.' },
        { topic: 'Enum', text: 'Lợi ích chính của enum DayOfWeek là gì?', options: ['Code rõ nghĩa hơn so với dùng số 0,1,2 cho ngày', 'Enum tự lưu danh sách động', 'Enum thay thế mọi vòng lặp', 'Enum bắt buộc đọc từ Console'], correct: 0, explanation: 'Enum giúp tránh magic number.' },
        { topic: 'Enum', text: 'Mảng int[] scores = new int[5]; có bao nhiêu phần tử?', options: ['5', '4', '6', 'Không xác định đến khi Add'], correct: 0, explanation: 'new int[5] tạo mảng cố định 5 phần tử.' },
        { topic: 'Enum', text: 'Chỉ số đầu tiên của int[] numbers = { 10, 20, 30 } là gì?', options: ['0', '1', '-1', 'numbers.Length'], correct: 0, explanation: 'Array trong C# bắt đầu từ index 0.' },
        { topic: 'Enum', text: 'Dòng nào lấy số phần tử của array numbers?', options: ['numbers.Length', 'numbers.Count', 'numbers.Size()', 'numbers.Total'], correct: 0, explanation: 'Array dùng thuộc tính Length.' },
        { topic: 'Enum', text: 'Dòng nào lấy số phần tử của List<string> names?', options: ['names.Count', 'names.Length', 'names.Size', 'names.Capacity()'], correct: 0, explanation: 'List<T> dùng Count để lấy số phần tử hiện có.' },
        { topic: 'Enum', text: 'Khi số lượng phần tử thường xuyên thêm/xóa, nên chọn gì?', options: ['List<T>', 'Array có kích thước cố định', 'Enum', 'char'], correct: 0, explanation: 'List<T> phù hợp danh sách động.' },
        { topic: 'Enum', text: 'Mảng răng cưa int[][] jagged khác int[,] matrix ở điểm nào?', options: ['Mỗi hàng của jagged có thể có độ dài khác nhau', 'jagged luôn chỉ có đúng 2 cột', 'matrix không truy cập được bằng chỉ số', 'jagged không lưu được int'], correct: 0, explanation: 'Jagged array là mảng của các mảng.' },

        { topic: 'Kế thừa', text: 'Cú pháp nào cho MiniVan kế thừa Car?', options: ['class MiniVan : Car { }', 'class MiniVan extends Car { }', 'class MiniVan inherits Car { }', 'class MiniVan(Car) { }'], correct: 0, explanation: 'C# dùng dấu hai chấm cho kế thừa class.' },
        { topic: 'Kế thừa', text: 'Member nào của Car mà MiniVan không truy cập trực tiếp được?', options: ['private int speed;', 'protected int speed;', 'public int speed;', 'public void Run()'], correct: 0, explanation: 'private chỉ dùng trực tiếp trong chính class khai báo.' },
        { topic: 'Kế thừa', text: 'Bạn muốn class con dùng được field speed nhưng code ngoài không dùng trực tiếp. Chọn access modifier nào?', options: ['protected', 'public', 'private', 'internal static constructor'], correct: 0, explanation: 'protected mở cho class cha và class con, không mở trực tiếp cho bên ngoài.' },
        { topic: 'Kế thừa', text: 'Tạo new MiniVan() khi Car và MiniVan đều có constructor in tên class. Thứ tự in đúng là gì?', options: ['Car trước, MiniVan sau', 'MiniVan trước, Car sau', 'Chỉ MiniVan', 'Chỉ Car'], correct: 0, explanation: 'Constructor class cha chạy trước constructor class con.' },
        { topic: 'Kế thừa', text: 'Employee chỉ có Employee(string name). Manager constructor không gọi base(name) sẽ ra sao?', options: ['Lỗi vì không có constructor Employee không tham số để gọi ngầm', 'Compiler tự truyền chuỗi rỗng cho Employee', 'Manager tự kế thừa Employee(string name)', 'Employee constructor bị bỏ qua'], correct: 0, explanation: 'Class con phải gọi constructor cha hợp lệ.' },
        { topic: 'Kế thừa', text: 'C# cho một class kế thừa trực tiếp từ bao nhiêu class cha?', options: ['Một class', 'Hai class', 'Không giới hạn', 'Một class cho mỗi method'], correct: 0, explanation: 'C# chỉ hỗ trợ kế thừa đơn với class.' },
        { topic: 'Kế thừa', text: 'Muốn không cho class khác kế thừa SecurityToken, dùng từ khóa nào?', options: ['sealed', 'protected', 'virtual', 'override'], correct: 0, explanation: 'sealed class không thể bị kế thừa.' },
        { topic: 'Kế thừa', text: 'Class con có kế thừa constructor của class cha không?', options: ['Không', 'Có, luôn kế thừa toàn bộ', 'Chỉ kế thừa private constructor', 'Chỉ kế thừa static constructor'], correct: 0, explanation: 'Constructor không được kế thừa như method/property.' },

        { topic: 'Đa hình', text: 'Cặp Add(int,int) và Add(double,double) trong cùng class là gì?', options: ['Overloading', 'Overriding', 'Constructor chaining', 'Static constructor'], correct: 0, explanation: 'Cùng tên, khác tham số trong cùng class là overloading.' },
        { topic: 'Đa hình', text: 'Shape có public virtual void Draw(), Circle có public override void Draw(). Đây là gì?', options: ['Overriding', 'Overloading', 'Boxing', 'Constructor overloading'], correct: 0, explanation: 'Class con ghi đè method virtual của class cha bằng override.' },
        { topic: 'Đa hình', text: 'Điều kiện để dùng override ở class con là gì?', options: ['Method ở class cha phải virtual, abstract hoặc override phù hợp', 'Method ở class cha phải private', 'Method ở class cha phải static', 'Method ở class cha phải là constructor'], correct: 0, explanation: 'override cần một method cha cho phép ghi đè.' },
        { topic: 'Đa hình', text: 'Shape s = new Circle(); s.Draw(); nếu Draw được override, method nào chạy?', options: ['Circle.Draw()', 'Shape.Draw() luôn luôn', 'Cả hai cùng chạy tự động', 'Không method nào chạy'], correct: 0, explanation: 'Đa hình lúc chạy chọn theo object thật.' },
        { topic: 'Đa hình', text: 'Overloading được phân biệt chủ yếu bằng gì?', options: ['Danh sách tham số', 'Kiểu trả về duy nhất', 'Tên biến nhận kết quả', 'Access modifier duy nhất'], correct: 0, explanation: 'Compiler chọn overload theo số lượng, kiểu hoặc thứ tự tham số.' },
        { topic: 'Đa hình', text: 'Overriding yêu cầu danh sách tham số của method con thế nào?', options: ['Giống method cha', 'Luôn nhiều hơn method cha một tham số', 'Luôn ít hơn method cha một tham số', 'Không được có tham số'], correct: 0, explanation: 'Override giữ cùng signature tương thích với method cha.' },
        { topic: 'Đa hình', text: 'Muốn trong Circle.Draw() gọi lại bản Draw của Shape, viết gì?', options: ['base.Draw();', 'this.base.Draw();', 'Shape.override.Draw();', 'virtual.Draw();'], correct: 0, explanation: 'base.Method() gọi triển khai từ class cha.' },
        { topic: 'Đa hình', text: 'Static method có override đa hình như instance virtual method không?', options: ['Không', 'Có, chỉ cần thêm override', 'Có, nếu method trả về void', 'Có, nếu class con sealed'], correct: 0, explanation: 'Static method không override theo cơ chế virtual dispatch của instance method.' },

        { topic: 'Phạm vi truy cập', text: 'private int age trong class Person truy cập được trực tiếp ở đâu?', options: ['Bên trong class Person', 'Từ mọi class con', 'Từ mọi object bên ngoài', 'Từ mọi namespace'], correct: 0, explanation: 'private giới hạn trong chính class khai báo.' },
        { topic: 'Phạm vi truy cập', text: 'public void Run() trong Car truy cập được từ đâu?', options: ['Từ code bên ngoài nếu nhìn thấy class Car', 'Chỉ bên trong Car', 'Chỉ trong class con của Car', 'Chỉ trong static constructor'], correct: 0, explanation: 'public là mức truy cập mở nhất.' },
        { topic: 'Phạm vi truy cập', text: 'protected string address trong Person truy cập trực tiếp được ở đâu?', options: ['Trong Person và class con như Student', 'Từ mọi object Student bên ngoài', 'Chỉ trong Main', 'Chỉ trong namespace System'], correct: 0, explanation: 'protected mở cho class khai báo và class con.' },
        { topic: 'Phạm vi truy cập', text: 'Student s = new Student(); s.address = "HCM"; nếu address protected trong Person thì sao?', options: ['Lỗi vì code ngoài không truy cập trực tiếp protected member', 'Đúng vì Student kế thừa Person', 'Đúng nếu address là string', 'Tự động gọi setter private'], correct: 0, explanation: 'protected không cho truy cập qua object từ bên ngoài.' },
        { topic: 'Phạm vi truy cập', text: 'Field lương salary nên để mức truy cập nào nếu cần kiểm tra trước khi sửa?', options: ['private field và public property kiểm tra', 'public field salary', 'protected public salary', 'namespace salary'], correct: 0, explanation: 'Dữ liệu nhạy cảm nên được đóng gói.' },
        { topic: 'Phạm vi truy cập', text: 'Helper method chỉ dùng nội bộ class Invoice nên khai báo thế nào?', options: ['private void CalculateTax() { }', 'public void CalculateTax() { }', 'protected static namespace CalculateTax', 'override void CalculateTax() { }'], correct: 0, explanation: 'private giữ method nội bộ khỏi API công khai.' },
        { topic: 'Phạm vi truy cập', text: 'Muốn class con đọc field code nhưng không muốn code ngoài đọc trực tiếp, chọn gì?', options: ['protected string code;', 'public string code;', 'private string code; không có API nào', 'static class code;'], correct: 0, explanation: 'protected phù hợp khi class con cần truy cập trực tiếp.' },
        { topic: 'Phạm vi truy cập', text: 'Vì sao public field thường kém hơn private field + property?', options: ['Public field cho phép bỏ qua toàn bộ logic kiểm tra dữ liệu', 'Public field không thể biên dịch trong C#', 'Property không thể đọc dữ liệu', 'Private field tự động lưu trên GitHub'], correct: 0, explanation: 'Property cho phép kiểm soát đọc/ghi, public field thì không.' },

        { topic: 'Dự đoán kết quả', text: 'int[] a = { 3, 5, 7 }; Console.WriteLine(a[1]); in gì?', options: ['5', '3', '7', 'Lỗi vì index bắt đầu từ 1'], correct: 0, explanation: 'Index 1 là phần tử thứ hai.' },
        { topic: 'Dự đoán kết quả', text: 'List<int> nums = new List<int>(); nums.Add(2); nums.Add(4); nums.Remove(2); Console.WriteLine(nums.Count); in gì?', options: ['1', '2', '0', 'Lỗi vì List không có Count'], correct: 0, explanation: 'Sau khi xóa 2, danh sách còn một phần tử.' },
        { topic: 'Dự đoán kết quả', text: 'Student.schoolName = "ABC"; s1.Name = "An"; s2.Name = "Binh"; in s2.Name + Student.schoolName được gì?', options: ['BinhABC', 'AnABC', 'Binhnull', 'ABCABC'], correct: 0, explanation: 'Name là instance field riêng của s2, schoolName là static dùng chung.' },
        { topic: 'Dự đoán kết quả', text: 'int x = 10; int y = x; y = 20; Console.WriteLine(x); in gì?', options: ['10', '20', '0', 'null'], correct: 0, explanation: 'int là value type, y nhận bản sao của x.' },
        { topic: 'Dự đoán kết quả', text: 'Car c1 = new Car(); Car c2 = c1; c2.Speed = 90; Console.WriteLine(c1.Speed); in gì?', options: ['90', '0', 'null', 'Lỗi vì class không gán được'], correct: 0, explanation: 'c1 và c2 tham chiếu cùng object Car.' },

        { topic: 'Phát hiện lỗi', text: 'Lỗi của public void Student() { } trong class Student là gì nếu muốn viết constructor?', options: ['Có void nên đây không phải constructor', 'Tên Student không được dùng trong class Student', 'Constructor bắt buộc static', 'Constructor bắt buộc có tham số'], correct: 0, explanation: 'Constructor không khai báo kiểu trả về.' },
        { topic: 'Phát hiện lỗi', text: 'Lỗi của static void M() { Console.WriteLine(name); } nếu name là instance field?', options: ['Static method không truy cập trực tiếp instance field name', 'Console.WriteLine không dùng được trong static method', 'name bắt buộc là int', 'void method không được gọi Console'], correct: 0, explanation: 'Static method không có this.' },
        { topic: 'Phát hiện lỗi', text: 'Lỗi của class C : A, B { } là gì?', options: ['C# không cho một class kế thừa trực tiếp hai class', 'Tên class C quá ngắn', 'A và B phải là enum', 'Dấu phẩy chỉ dùng trong constructor'], correct: 0, explanation: 'C# chỉ hỗ trợ kế thừa đơn với class.' },
        { topic: 'Phát hiện lỗi', text: 'Lỗi của int Add(int a,int b) và float Add(int x,int y) trong cùng class là gì?', options: ['Hai method chỉ khác kiểu trả về', 'Tên tham số không giống nhau', 'float không được return trong method', 'int không được overload'], correct: 0, explanation: 'Overload không phân biệt bằng kiểu trả về.' },
        { topic: 'Phát hiện lỗi', text: 'Lỗi của Console.WriteLine(names.Length); nếu names là List<string> là gì?', options: ['List<T> dùng Count, không dùng Length', 'List<T> không in được ra Console', 'Length chỉ dùng cho int', 'names phải là static'], correct: 0, explanation: 'Array dùng Length, List<T> dùng Count.' }
    ];

    function renderQuestion(q, index) {
        const optionLines = q.options.map((option, i) => `- [${i === q.correct ? 'x' : ' '}] ${option}`).join('\n');
        return `## Câu ${index + 1}
Chủ đề: ${q.topic}
${q.text}

${optionLines}

> Giải thích: ${q.explanation}`;
    }

    window.topicQuestionBankData = `# Trắc nghiệm theo chủ đề - 100 câu cụ thể từ tài liệu ktlt.docx

${questions.map(renderQuestion).join('\n\n')}`;
})();
